football_players = ["Lionel Messi", "Cristiano Ronaldo", "Neymar Jr.", "Kylian Mbappe", "Kevin De Bruyne"]
print(football_players)
print(sorted(football_players))
print(football_players)
football_players.reverse()
print(football_players)
football_players.reverse()
print(football_players)
football_players.sort()
print(football_players)
football_players.sort(reverse=True)
print(football_players)
print(len(football_players))
football_players.remove("Neymar Jr.")
print(football_players)
removed = football_players.pop(1)
print(removed)
print(football_players)
del football_players[0]
print(football_players)
football_players.insert(0, "Erling Haaland")
print(football_players)
football_players.append("Mohamed Salah")
print(football_players)
football_players[0] = "Robert Lewandowski"
print(football_players)
print(football_players[0].lower())
print(football_players[0])